apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - httproute.yaml
  - nginx-gateway-install.yaml

commonLabels:
  app: sample-serve
