apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-serve
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/${GITHUB_REPOSITORY}.git
    targetRevision: HEAD
    path: gitops/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
    - name: Description
      value: Sample Serve Application with NGINX Gateway
    - name: Maintainer
      value: DevOps Team
